module.exports = {
  apps: [
    {
      name: "chat-ui",
      cwd: "./chat-ui",
      script: "npm",
      args: "run dev",
      env: {
        NODE_ENV: "development",
        PORT: 8001,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      log_file: "./logs/chat-ui.log",
      out_file: "./logs/chat-ui-out.log",
      error_file: "./logs/chat-ui-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "chat-core",
      cwd: "./chat-core",
      script: "npm",
      args: "run dev",
      env: {
        NODE_ENV: "development",
        PORT: 8002,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      log_file: "./logs/chat-core.log",
      out_file: "./logs/chat-core-out.log",
      error_file: "./logs/chat-core-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "ai-service",
      cwd: "./ai-service",
      script: "npm",
      args: "run dev",
      env: {
        NODE_ENV: "development",
        PORT: 8003,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      log_file: "./logs/ai-service.log",
      out_file: "./logs/ai-service-out.log",
      error_file: "./logs/ai-service-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "chat-session",
      cwd: "./chat-session",
      script: "npm",
      args: "run dev",
      env: {
        NODE_ENV: "development",
        PORT: 8004,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      log_file: "./logs/chat-session.log",
      out_file: "./logs/chat-session-out.log",
      error_file: "./logs/chat-session-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "chat-admin",
      cwd: "./chat-admin",
      script: "npm",
      args: "run dev",
      env: {
        NODE_ENV: "development",
        PORT: 8005,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      log_file: "./logs/chat-admin.log",
      out_file: "./logs/chat-admin-out.log",
      error_file: "./logs/chat-admin-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "chat-admin-ui",
      cwd: "./chat-admin-ui",
      script: "npm",
      args: "run start:dev",
      env: {
        NODE_ENV: "development",
        PORT: 8006,
        MAX_PORT: 8006,
        BROWSER: "none",
        REACT_APP_ENV: "dev",
        MOCK: "none",
        UMI_ENV: "dev",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      log_file: "./logs/chat-admin-ui.log",
      out_file: "./logs/chat-admin-ui-out.log",
      error_file: "./logs/chat-admin-ui-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],

  // 部署配置 (可选)
  deploy: {
    production: {
      user: "ubuntu",
      host: ["your-server.com"],
      ref: "origin/main",
      repo: "https://github.com/your-org/OpenChatAgent.git",
      path: "/var/www/OpenChatAgent",
      "post-deploy":
        "npm install && npm run build && pm2 reload ecosystem.config.js --env production",
    },
  },
};
